CREATE DATABASE IF NOT EXISTS aura_ai_db;
USE aura_ai_db;

CREATE TABLE IF NOT EXISTS pending_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    date VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS approved_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    photo LONGTEXT
);

CREATE TABLE IF NOT EXISTS rejected_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    date VARCHAR(50) NOT NULL
);
